insert into public.subjects (id, name, topic, icon, color, grade, sort_order) values
  ('grade-1-english', 'English Language Activities', 'Listening, speaking, reading and writing', 'Aa', 'navy', 'Grade 1', 1),
  ('grade-1-kiswahili', 'Kiswahili Language Activities', 'Listening and speaking in Kiswahili', 'Kw', 'teal', 'Grade 1', 2),
  ('grade-1-mathematics', 'Mathematics Activities', 'Numbers and basic operations', '∑', 'gold', 'Grade 1', 3),
  ('grade-1-environment', 'Environmental Activities', 'Nature, health and safety', '✳', 'green', 'Grade 1', 4),
  ('grade-1-creative', 'Creative Activities', 'Drawing, music and movement', '✦', 'navy', 'Grade 1', 5),
  ('grade-1-religious', 'Religious Education Activities', 'Faith, values and morality', '☼', 'teal', 'Grade 1', 6),
  ('grade-1-indigenous', 'Indigenous Languages', 'Local language and cultural identity', '語', 'gold', 'Grade 1', 7),
  ('grade-10-english', 'English', 'Communication and literary analysis', 'Aa', 'navy', 'Grade 10', 1),
  ('grade-10-kiswahili', 'Kiswahili', 'Language and expression', 'Kw', 'teal', 'Grade 10', 2),
  ('grade-10-mathematics', 'Mathematics', 'Core quantitative reasoning', '∑', 'gold', 'Grade 10', 3),
  ('grade-10-biology', 'Biology', 'Cell and organism systems', 'Bio', 'green', 'Grade 10', 4),
  ('grade-10-chemistry', 'Chemistry', 'Matter and reactions', 'Ch', 'teal', 'Grade 10', 5),
  ('grade-10-physics', 'Physics', 'Energy and motion', 'Phy', 'navy', 'Grade 10', 6),
  ('grade-10-computer-studies', 'Computer Studies', 'Digital literacy and computing', '💻', 'gold', 'Grade 10', 7),
  ('grade-10-agriculture', 'Agriculture', 'Production and agribusiness', '❋', 'green', 'Grade 10', 8),
  ('grade-10-geography', 'Geography', 'Earth and environmental systems', 'Geo', 'navy', 'Grade 10', 9),
  ('grade-10-history-citizenship', 'History and Citizenship', 'Kenya, society and governance', 'Hist', 'teal', 'Grade 10', 10),
  ('grade-10-business-studies', 'Business Studies', 'Entrepreneurship and commerce', 'Biz', 'gold', 'Grade 10', 11),
  ('grade-10-economics', 'Economics', 'Resources and decision making', 'Eco', 'green', 'Grade 10', 12),
  ('grade-10-music', 'Music and Dance', 'Performance and cultural arts', '♫', 'navy', 'Grade 10', 13),
  ('grade-10-visual-arts', 'Visual Arts', 'Art, design and creativity', '✦', 'gold', 'Grade 10', 14),
  ('grade-10-physical-education', 'Physical Education and Sports', 'Wellbeing and sportsmanship', '⚽', 'teal', 'Grade 10', 15),
  ('grade-10-religious', 'Religious Education', 'Faith, values and service', '☼', 'navy', 'Grade 10', 16),
  ('grade-10-community-service', 'Community Service Learning', 'Service and civic engagement', '◎', 'green', 'Grade 10', 17),
  ('grade-10-ict-skills', 'ICT Skills', 'Digital literacy, communication and responsible technology use', 'ICT', 'teal', 'Grade 10', 18),
  ('grade-11-english', 'English', 'Advanced writing and analysis', 'Aa', 'navy', 'Grade 11', 1),
  ('grade-11-kiswahili', 'Kiswahili', 'Language mastery and literature', 'Kw', 'teal', 'Grade 11', 2),
  ('grade-11-mathematics', 'Mathematics', 'Functions, sequences and applications', '∑', 'gold', 'Grade 11', 3),
  ('grade-11-biology', 'Biology', 'Human systems and life science', 'Bio', 'green', 'Grade 11', 4),
  ('grade-11-chemistry', 'Chemistry', 'Organic and inorganic chemistry', 'Ch', 'teal', 'Grade 11', 5),
  ('grade-11-physics', 'Physics', 'Mechanics, electricity and waves', 'Phy', 'navy', 'Grade 11', 6),
  ('grade-11-computer-studies', 'Computer Studies', 'Programming and systems', '💻', 'gold', 'Grade 11', 7),
  ('grade-11-agriculture', 'Agriculture', 'Crop science and agribusiness', '❋', 'green', 'Grade 11', 8),
  ('grade-11-geography', 'Geography', 'Humans and the environment', 'Geo', 'navy', 'Grade 11', 9),
  ('grade-11-history-citizenship', 'History and Citizenship', 'Governance and society', 'Hist', 'teal', 'Grade 11', 10),
  ('grade-11-business-studies', 'Business Studies', 'Finance and enterprise', 'Biz', 'gold', 'Grade 11', 11),
  ('grade-11-economics', 'Economics', 'Economic systems and development', 'Eco', 'green', 'Grade 11', 12),
  ('grade-11-music', 'Music and Dance', 'Performance and expression', '♫', 'navy', 'Grade 11', 13),
  ('grade-11-theatre', 'Theatre and Film', 'Drama, media and storytelling', '🎭', 'gold', 'Grade 11', 14),
  ('grade-11-visual-arts', 'Visual Arts', 'Creative production', '✦', 'navy', 'Grade 11', 15),
  ('grade-11-physical-education', 'Physical Education and Sports', 'Fitness and team sport', '⚽', 'teal', 'Grade 11', 16),
  ('grade-11-religious', 'Religious Education', 'Ethics and social responsibility', '☼', 'navy', 'Grade 11', 17),
  ('grade-11-community-service', 'Community Service Learning', 'Service and community action', '◎', 'green', 'Grade 11', 18),
  ('grade-11-ict-skills', 'ICT Skills', 'Digital systems, information and responsible technology use', 'ICT', 'teal', 'Grade 11', 19),
  ('grade-12-english', 'English', 'Critical reading and writing', 'Aa', 'navy', 'Grade 12', 1),
  ('grade-12-kiswahili', 'Kiswahili', 'Advanced literature and language', 'Kw', 'teal', 'Grade 12', 2),
  ('grade-12-mathematics', 'Mathematics', 'Applications and analytical reasoning', '∑', 'gold', 'Grade 12', 3),
  ('grade-12-biology', 'Biology', 'Genetics and ecosystems', 'Bio', 'green', 'Grade 12', 4),
  ('grade-12-chemistry', 'Chemistry', 'Chemical systems and analysis', 'Ch', 'teal', 'Grade 12', 5),
  ('grade-12-physics', 'Physics', 'Modern physics and applications', 'Phy', 'navy', 'Grade 12', 6),
  ('grade-12-computer-studies', 'Computer Studies', 'Systems design and digital problem solving', '💻', 'gold', 'Grade 12', 7),
  ('grade-12-agriculture', 'Agriculture', 'Agribusiness and sustainability', '❋', 'green', 'Grade 12', 8),
  ('grade-12-geography', 'Geography', 'Resource use and development', 'Geo', 'navy', 'Grade 12', 9),
  ('grade-12-history-citizenship', 'History and Citizenship', 'Law, identity and citizenship', 'Hist', 'teal', 'Grade 12', 10),
  ('grade-12-business-studies', 'Business Studies', 'Enterprise and management', 'Biz', 'gold', 'Grade 12', 11),
  ('grade-12-economics', 'Economics', 'Markets, policy and growth', 'Eco', 'green', 'Grade 12', 12),
  ('grade-12-music', 'Music and Dance', 'Performance and cultural practice', '♫', 'navy', 'Grade 12', 13),
  ('grade-12-theatre', 'Theatre and Film', 'Production and storytelling', '🎭', 'gold', 'Grade 12', 14),
  ('grade-12-visual-arts', 'Visual Arts', 'Portfolio and design practice', '✦', 'navy', 'Grade 12', 15),
  ('grade-12-physical-education', 'Physical Education and Sports', 'Performance and leadership', '⚽', 'teal', 'Grade 12', 16),
  ('grade-12-religious', 'Religious Education', 'Leadership and values', '☼', 'navy', 'Grade 12', 17),
  ('grade-12-community-service', 'Community Service Learning', 'Public service and reflection', '◎', 'green', 'Grade 12', 18),
  ('grade-12-ict-skills', 'ICT Skills', 'Digital systems, information and responsible technology use', 'ICT', 'teal', 'Grade 12', 19),
  ('grade-2-english', 'English Language Activities', 'Reading fluency and sentence building', 'Aa', 'navy', 'Grade 2', 1),
  ('grade-2-kiswahili', 'Kiswahili Language Activities', 'Vocabulary and communication', 'Kw', 'teal', 'Grade 2', 2),
  ('grade-2-mathematics', 'Mathematics Activities', 'Addition, subtraction and patterns', '∑', 'gold', 'Grade 2', 3),
  ('grade-2-environment', 'Environmental Activities', 'People, plants and weather', '✳', 'green', 'Grade 2', 4),
  ('grade-2-creative', 'Creative Activities', 'Art and imagination', '✦', 'navy', 'Grade 2', 5),
  ('grade-2-religious', 'Religious Education Activities', 'Values and respectful living', '☼', 'teal', 'Grade 2', 6),
  ('grade-2-indigenous', 'Indigenous Languages', 'Local language and culture', '語', 'gold', 'Grade 2', 7),
  ('grade-3-english', 'English Language Activities', 'Comprehension and storytelling', 'Aa', 'navy', 'Grade 3', 1),
  ('grade-3-kiswahili', 'Kiswahili Language Activities', 'Listening, writing and confidence', 'Kw', 'teal', 'Grade 3', 2),
  ('grade-3-mathematics', 'Mathematics Activities', 'Place value and problem solving', '∑', 'gold', 'Grade 3', 3),
  ('grade-3-environment', 'Environmental Activities', 'Our environment and everyday life', '✳', 'green', 'Grade 3', 4),
  ('grade-3-creative', 'Creative Activities', 'Art, music and physical play', '✦', 'navy', 'Grade 3', 5),
  ('grade-3-religious', 'Religious Education Activities', 'Good conduct and character', '☼', 'teal', 'Grade 3', 6),
  ('grade-3-indigenous', 'Indigenous Languages', 'Culture, stories and identity', '語', 'gold', 'Grade 3', 7),
  ('grade-4-english', 'English', 'Reading, writing and grammar', 'Aa', 'navy', 'Grade 4', 1),
  ('grade-4-kiswahili', 'Kiswahili', 'Communication and grammar', 'Kw', 'teal', 'Grade 4', 2),
  ('grade-4-mathematics', 'Mathematics', 'Operations and problem solving', '∑', 'gold', 'Grade 4', 3),
  ('grade-4-science', 'Science and Technology', 'Scientific thinking and innovation', '✳', 'green', 'Grade 4', 4),
  ('grade-4-social', 'Social Studies', 'People, communities and citizenship', '◌', 'navy', 'Grade 4', 5),
  ('grade-4-agriculture', 'Agriculture', 'Crops, plants and food production', '❋', 'green', 'Grade 4', 6),
  ('grade-4-home-science', 'Home Science', 'Family, hygiene and life skills', '⌂', 'gold', 'Grade 4', 7),
  ('grade-4-creative-arts', 'Creative Arts', 'Arts, craft and expression', '✦', 'navy', 'Grade 4', 8),
  ('grade-4-religious', 'Religious Education', 'Values and faith practice', '☼', 'teal', 'Grade 4', 9),
  ('grade-5-english', 'English', 'Reading and writing for meaning', 'Aa', 'navy', 'Grade 5', 1),
  ('grade-5-kiswahili', 'Kiswahili', 'Vocabulary, listening and speaking', 'Kw', 'teal', 'Grade 5', 2),
  ('grade-5-mathematics', 'Mathematics', 'Number fluency and reasoning', '∑', 'gold', 'Grade 5', 3),
  ('grade-5-science', 'Science and Technology', 'Investigations and technology', '✳', 'green', 'Grade 5', 4),
  ('grade-5-social', 'Social Studies', 'Governance and geography', '◌', 'navy', 'Grade 5', 5),
  ('grade-5-agriculture', 'Agriculture', 'Soil, crops and animal care', '❋', 'green', 'Grade 5', 6),
  ('grade-5-home-science', 'Home Science', 'Nutrition and household skills', '⌂', 'gold', 'Grade 5', 7),
  ('grade-5-creative-arts', 'Creative Arts', 'Music, drawing and performance', '✦', 'navy', 'Grade 5', 8),
  ('grade-5-religious', 'Religious Education', 'Values and community responsibility', '☼', 'teal', 'Grade 5', 9),
  ('grade-6-english', 'English', 'Language, comprehension and composition', 'Aa', 'navy', 'Grade 6', 1),
  ('maths', 'Mathematics', 'Fractions & decimals', '∑', 'teal', 'Grade 6', 1),
  ('grade-6-kiswahili', 'Kiswahili', 'Language use and communication', 'Kw', 'teal', 'Grade 6', 2),
  ('science', 'Integrated Science', 'Living things & their environment', '✳', 'mint', 'Grade 6', 2),
  ('english', 'English', 'Creative writing', 'Aa', 'peach', 'Grade 6', 3),
  ('grade-6-mathematics', 'Mathematics', 'Fractions, decimals and data', '∑', 'gold', 'Grade 6', 3),
  ('grade-6-science', 'Science and Technology', 'Systems, energy and innovation', '✳', 'green', 'Grade 6', 4),
  ('grade-6-social', 'Social Studies', 'History, citizenship and environment', '◌', 'navy', 'Grade 6', 5),
  ('grade-6-agriculture', 'Agriculture', 'Food systems and crop production', '❋', 'green', 'Grade 6', 6),
  ('grade-6-home-science', 'Home Science', 'Nutrition and home management', '⌂', 'gold', 'Grade 6', 7),
  ('grade-6-creative-arts', 'Creative Arts', 'Art, music and sports', '✦', 'navy', 'Grade 6', 8),
  ('grade-6-religious', 'Religious Education', 'Spiritual values and ethics', '☼', 'teal', 'Grade 6', 9),
  ('grade-7-english', 'English', 'Reading and language analysis', 'Aa', 'navy', 'Grade 7', 1),
  ('grade-7-kiswahili', 'Kiswahili', 'Oral, written and grammatical skills', 'Kw', 'teal', 'Grade 7', 2),
  ('grade-7-mathematics', 'Mathematics', 'Algebra, geometry and measures', '∑', 'gold', 'Grade 7', 3),
  ('grade-7-integrated-science', 'Integrated Science', 'Life, physical and earth science', '✳', 'green', 'Grade 7', 4),
  ('grade-7-social-studies', 'Social Studies', 'Citizenship, history and geography', '◌', 'navy', 'Grade 7', 5),
  ('grade-7-agriculture-nutrition', 'Agriculture and Nutrition', 'Production and healthy living', '❋', 'green', 'Grade 7', 6),
  ('grade-7-pre-technical', 'Pre-Technical Studies', 'Design, technology and safety', '⚙', 'gold', 'Grade 7', 7),
  ('grade-7-creative-arts-sports', 'Creative Arts and Sports', 'Expression and physical wellness', '✦', 'navy', 'Grade 7', 8),
  ('grade-7-religious', 'Religious Education', 'Values, ethics and community life', '☼', 'teal', 'Grade 7', 9),
  ('grade-8-english', 'English', 'Literature, grammar and communication', 'Aa', 'navy', 'Grade 8', 1),
  ('grade-8-kiswahili', 'Kiswahili', 'Language fluency and composition', 'Kw', 'teal', 'Grade 8', 2),
  ('grade-8-mathematics', 'Mathematics', 'Numbers, equations and geometry', '∑', 'gold', 'Grade 8', 3),
  ('grade-8-integrated-science', 'Integrated Science', 'Scientific inquiry and applications', '✳', 'green', 'Grade 8', 4),
  ('grade-8-social-studies', 'Social Studies', 'Societies and governance', '◌', 'navy', 'Grade 8', 5),
  ('grade-8-agriculture-nutrition', 'Agriculture and Nutrition', 'Food security and healthy habits', '❋', 'green', 'Grade 8', 6),
  ('grade-8-pre-technical', 'Pre-Technical Studies', 'Materials and making', '⚙', 'gold', 'Grade 8', 7),
  ('grade-8-creative-arts-sports', 'Creative Arts and Sports', 'Creativity, sport and teamwork', '✦', 'navy', 'Grade 8', 8),
  ('grade-8-religious', 'Religious Education', 'Ethics and cultural understanding', '☼', 'teal', 'Grade 8', 9),
  ('grade-9-english', 'English', 'Advanced language and literature', 'Aa', 'navy', 'Grade 9', 1),
  ('grade-9-kiswahili', 'Kiswahili', 'Language complexity and expression', 'Kw', 'teal', 'Grade 9', 2),
  ('grade-9-mathematics', 'Mathematics', 'Algebra, probability and geometry', '∑', 'gold', 'Grade 9', 3),
  ('grade-9-integrated-science', 'Integrated Science', 'Research and problem solving', '✳', 'green', 'Grade 9', 4),
  ('grade-9-social-studies', 'Social Studies', 'Citizenship and national identity', '◌', 'navy', 'Grade 9', 5),
  ('grade-9-agriculture-nutrition', 'Agriculture and Nutrition', 'Sustainability and health', '❋', 'green', 'Grade 9', 6),
  ('grade-9-pre-technical', 'Pre-Technical Studies', 'Practical problem solving', '⚙', 'gold', 'Grade 9', 7),
  ('grade-9-creative-arts-sports', 'Creative Arts and Sports', 'Performance and wellbeing', '✦', 'navy', 'Grade 9', 8),
  ('grade-9-religious', 'Religious Education', 'Ethics, service and belief', '☼', 'teal', 'Grade 9', 9)
on conflict (id) do nothing;

insert into public.lessons (id, subject_id, content_type, title, summary, content, sort_order) values
  ('english-description', 'english', 'lesson', 'Writing a description', 'Use specific words to help a reader imagine a place.', 'A clear description uses details gathered through the senses. Choose precise nouns and verbs, then add a few details about colour, sound, texture, or movement.', 1),
  ('english-edit', 'english', 'lesson', 'Reviewing your writing', 'Make a draft clearer with a careful review.', 'Read your work slowly. Check that each sentence is complete, ideas follow a sensible order, punctuation helps the reader, and spelling is checked for familiar words.', 3),
  ('english-story', 'english', 'lesson', 'Planning a short story', 'Give a story a beginning, a problem, and a resolution.', 'Before writing, decide who the story is about, where it happens, and what challenge the character faces. A simple plan helps events follow a clear order.', 2),
  ('maths-decimals', 'maths', 'lesson', 'Fractions as decimals', 'Connect tenths and hundredths to decimal notation.', 'A decimal point separates whole numbers from parts of a whole. One tenth is 0.1 and one hundredth is 0.01. You can use place value to compare decimal numbers.', 3),
  ('maths-equivalent', 'maths', 'lesson', 'Equivalent fractions', 'Different fractions can show the same amount.', 'Equivalent fractions have the same value. Multiply or divide both the numerator and denominator by the same number. For example, 1/2 and 2/4 describe the same amount.', 2),
  ('maths-fractions', 'maths', 'lesson', 'Understanding fractions', 'See how equal parts make a whole.', 'A fraction names equal parts of a whole. The top number counts the parts you have; the bottom number counts the equal parts in the whole. For example, 3/4 means three of four equal parts.', 1),
  ('science-care', 'science', 'lesson', 'Caring for our environment', 'Identify practical ways to protect habitats.', 'People can care for habitats by reducing litter, using resources responsibly, planting suitable native plants, and protecting places where living things feed and reproduce.', 3),
  ('science-food-chains', 'science', 'lesson', 'Food chains', 'Follow how energy moves between living things.', 'A food chain shows how energy passes from one organism to another. Green plants make their own food, herbivores eat plants, and predators may eat other animals.', 2),
  ('science-habitats', 'science', 'lesson', 'Habitats and living things', 'Explore how habitats support organisms.', 'A habitat is the place where an organism lives. It provides resources such as food, water, shelter, and space. Different organisms are suited to different habitats.', 1)
on conflict (id) do nothing;

insert into public.assessments (id, title, subject_id, kind, duration_minutes, opens_at, published, created_by) values
  ('maths-practice', 'Mathematics practice', 'grade-6-mathematics', 'PRACTICE', 20, now() + interval '2 days', true, null),
  ('science-check', 'Science quick check', 'grade-6-science', 'QUIZ', 20, now() + interval '5 days', true, null)
on conflict (id) do nothing;

insert into public.questions (id, assessment_id, prompt, options_json, correct_option, points, sort_order) values
  ('maths-practice-q1', 'maths-practice', 'What is 1/2 + 1/4?', '["1/6", "3/4", "2/6", "1"]'::jsonb, 1, 1, 1),
  ('maths-practice-q2', 'maths-practice', 'Which decimal is equal to 3/4?', '["0.25", "0.5", "0.75", "1.25"]'::jsonb, 2, 1, 2),
  ('science-check-q1', 'science-check', 'Which part of a plant absorbs water?', '["Flower", "Leaf", "Root", "Fruit"]'::jsonb, 2, 1, 1)
on conflict (id) do nothing;
